### PR TITLE
added cell types

### PR DESCRIPTION
**Pull request by vzinche**
@K-Meech I've also added cells I've used as a training set and corrected some obvious errors, so this version is slightly different from what I've sent you before

### CODE REVIEW

**Comment by K-Meech** [comment]
Great! Can we also add a version somewhere that is the exact same as the one you sent me too? Some people may want to reproduce the violin plots etc that we show in the paper, so it'd be good to have a dataset that matches. Also, I was going to add a supplemental table with the number of labelled cells per cell type, and it's confusing if the numbers in the paper and the table don't align.

**Comment by vzinche** [comment]
@constantinpape are we planning to have 1.0.2 at any moment?
If not, I could also just replace this one with the old version

**Comment by constantinpape** [comment]
@vzinche I think 1.0.2 will not come very soon, so I would stick with 1.0.1.

**Review by constantinpape — APPROVED** [review]

**Comment by vzinche** [comment]
@K-Meech, should I then just replace this version with the previous one (the one you had?)

**Comment by K-Meech** [comment]
@vzinche If you're happy to - I just think it would make it easier for people to connect the figures we made to the raw data. The only changes I made were removing the error & other 'dark' categories.

**Pull request merged**
